/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fenetre.java
 *
 * Created on 21 déc. 2012, 11:55:17
 */
package tetris.view;


import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import tetris.Controle;
import tetris.Figure;
import tetris.Grille;
/**
 *
 * @author zero
 */
public class JouerSeul extends javax.swing.JFrame implements KeyListener {
    private Figure fig_;
    private Figure fig_next_;
    private int delai_=1000;
    private Grille grille_;
    private JPanel affichage_;
    private JPanel affichage_fig;
    JFrame j;

    /** Creates new form Fenetre */
    public JouerSeul(Grille g) {
        
        initComponents();        
        //new AddKeyListener(this);
        jLabel3.setVisible(false);        
        jTextPane2.setEditable(false);
        grille_=g;
        affichage_=grille_.afficheGrille();
        affichage_.setBounds(0,0,251,551);
        jPanel2.setBackground(Color.black);
        jPanel2.add(affichage_);       
        affichage_.setBackground(Color.black);
        jLabel1.setText(""+grille_.getScore());
        jLabel2.setText(""+grille_.getDifficulté());
        
        //next figure                   
        fig_next_=Controle.newFigure();//new L();
        
       
        fig_=fig_next_;
        //
        addKeyListener(this); 
        addWindowListener(new WindowAdapter() {
	public void windowOpened(WindowEvent e) { 
	requestFocus();	
	}
	});
        jCheckBox1.addActionListener(new JCheckBoxListener(grille_,affichage_
                ,jCheckBox1));
        if(Controle.couleure_dalt==1){
           jCheckBox1.doClick(); 
        }
        jButton2.setVisible(false);
    }
    
    
private Timer timer = new Timer(delai_, new ActionListener() {
public void actionPerformed(ActionEvent e) {
//Inserer ici le code a repeter
    try{
    fig_.descendre(grille_);
    //System.out.println("try      :"+test++);
    }
    catch (Exception ex) {
        
        if((grille_.lireGrille(4, 0)!=null)
                    ||(grille_.lireGrille(5, 0)!=null)){
            
                jLabel3.setVisible(true);                
                //affichage_.setVisible(false);
                affichage_.add(jLabel3);
                affichage_.repaint();
                //affichage_.setEnabled(true);
                timer.stop();
                jButton2.setVisible(true);
                //System.out.println("je suis là");
                return;
                }           
            //timer.stop();
            Controle.simul(grille_);
            delai_=Controle.delay(grille_);
            timer.setDelay(delai_);
            jLabel1.setText(""+grille_.getScore());
            jLabel2.setText(""+grille_.getDifficulté());            
            affichage_.repaint();            
            fig_=fig_next_;
            fig_next_=Controle.newFigure();           
            //timer.start();          
                affichage_fig=fig_next_.afficheFigure();                
                jPanel3.add(affichage_fig);
                affichage_fig.repaint();
                affichage_fig.setBounds(0,0,101,101);
                affichage_fig.setBackground(Color.black);
                //System.out.println("fig"+fig_+"   "+test);
               // System.out.println("fig next "+fig_next_);
                
            }
    finally{        
        affichage_.repaint();
        //System.out.println("finaly:   "+fig_+"   "+test);
        }    
    }
}
);
public void simulatoin(){        
    fig_next_=Controle.newFigure();//new Z();/new L();
    affichage_fig=fig_next_.afficheFigure();
    jPanel3.add(affichage_fig);
    affichage_fig.repaint();
    affichage_fig.setBounds(0,0,101,101);
    affichage_fig.setBackground(Color.black);    
    timer.start();
    
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Option"));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("couleurs Daltonien");

        jTextPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Touches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jTextPane2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextPane2.setText("Boutons de Gameplay du joueur 1 :\n \n• LEFT : touche directionnelle gauche \n• RIGHT : touche directionnelle droite \n• ROTATE : touche directionnelle haut\n• DOWN : touche directionnelle bas");
        jTextPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextPane2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Quitter la partie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(251, 551));

        jLabel3.setBackground(new java.awt.Color(204, 255, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("!!GAME OVER!!");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(245, 245, 245))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Score:"));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Difficulté:"));
        jLabel2.setOpaque(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Next figure "));
        jPanel3.setPreferredSize(new java.awt.Dimension(101, 101));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jLabel4.setText("Echap: pour aller dans Option");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Rejouer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    j.setVisible(false);
    this.setVisible(false);
    Accueil a = new Accueil();
                a.setVisible(true);
                a.setLocationRelativeTo(null);
                a.setResizable(false);
                a.setTitle("Tetris_like"); 
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    JouerSeul f=new JouerSeul(new Grille());
                f.setVisible(true);
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setTitle("Tetris_like");                
                f.simulatoin();
    
}//GEN-LAST:event_jButton2ActionPerformed
 


    

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JouerSeul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JouerSeul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JouerSeul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JouerSeul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JouerSeul f=new JouerSeul(new Grille());
                f.setVisible(true);
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setTitle("Tetris_like");                
                f.simulatoin();
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        if(e.getKeyCode()==KeyEvent.VK_DOWN)
        {timer.setDelay(25);}
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
         if(e.getKeyCode()==KeyEvent.VK_DOWN)
        {timer.setDelay(50);}
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(timer.isRunning()){
         if(e.getKeyCode()==KeyEvent.VK_LEFT)
        {fig_.deplacerGauche(grille_);
             affichage_.repaint();}
         else if(e.getKeyCode()==KeyEvent.VK_RIGHT)
        {
          fig_.deplacerDroite(grille_);
            affichage_.repaint();
        }
         else if(e.getKeyCode()==KeyEvent.VK_UP)
        {
          fig_.rotate(grille_);
            affichage_.repaint();
        }
         else if(e.getKeyCode()==KeyEvent.VK_DOWN)
        {timer.setDelay(delai_);}
         
        }
        if(e.getKeyCode()==KeyEvent.VK_ESCAPE){
            if(timer.isRunning()){
            timer.stop();
            j= new JFrame();
            j.add(jPanel5);
            j.setVisible(true);            
            // taille et position
            j.setSize(380,300);
            j.setLocationRelativeTo(j.getParent());
            j.setResizable(false);
            jPanel5.setVisible(true);
            j.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e){ 
                timer.start();
                    requestFocus();	
                }
                }); 
            }    
        }
         
        //throw new UnsupportedOperationException("Not supported yet.");
    }/*
    private class JCheckBoxListener implements ActionListener {
    public void actionPerformed(ActionEvent e) {
        Color violet=new Color(200, 30, 240);
        Color blueCadet= new Color(95,158,160);// Cadet Blue
        Color gryDim=new Color(105,105,105);//Dim Gray
        Color cornsilk=new Color(205,200,177);//Cornsilk 3
       if(jCheckBox1.isSelected()){
    Controle.couleure_dalt=1;
    for(int i=0;i<10;i++){
        for(int j=0;j<22;j++){
            if(grille_.lireGrille(i, j)==Color.BLUE){
               grille_.lire_case_Grille(i, j).setCouleur(new Color(95,158,160));
            }
            if(grille_.lireGrille(i, j)==Color.RED){
              grille_.lire_case_Grille(i, j).setCouleur(new Color(105,105,105));
            }
            if(grille_.lireGrille(i, j)==violet){
              grille_.lire_case_Grille(i, j).setCouleur(new Color(205,200,177));
            }
        }        
            //repaint les figures
        
        /* for(i=0;i<4;i++){
               /*if(fig_.getCases(i).getCouleur()==Color.BLUE){
                   fig_.getCases(i).setCouleur(new Color(95,158,160));
                }
                if(fig_.getCases(i).getCouleur()==Color.RED){
                  fig_.getCases(i).setCouleur(new Color(105,105,105));
                }
                if(fig_.getCases(i).getCouleur()==violet){
                  fig_.getCases(i).setCouleur(new Color(205,200,177));
                }
                if(fig_next_.getCases(i).getCouleur()==Color.BLUE){
                   fig_next_.getCases(i).setCouleur(new Color(95,158,160));
                }
                if(fig_next_.getCases(i).getCouleur()==Color.RED){
                  fig_next_.getCases(i).setCouleur(new Color(105,105,105));
                }
                if(fig_next_.getCases(i).getCouleur()==violet){
                  fig_next_.getCases(i).setCouleur(new Color(205,200,177));
                }
            }
    //affichage_fig.repaint();
    affichage_.repaint();
    }
       } 
    else{
        Controle.couleure_dalt=0;
    for(int i=0;i<10;i++){
        for(int j=0;j<22;j++){
            if(grille_.lireGrille(i, j)==blueCadet){
               grille_.lire_case_Grille(i, j).setCouleur(Color.BLUE);
            }
            if(grille_.lireGrille(i, j)==gryDim){
              grille_.lire_case_Grille(i, j).setCouleur(Color.RED);
            }
            if(grille_.lireGrille(i, j)==cornsilk){
              grille_.lire_case_Grille(i, j).setCouleur(new Color(200, 30, 240));
            }
        }
    }
    affichage_.repaint();
    }
    }
}*/
}

